name: Build Water Watch Pro Remote BIN

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'remote/**'
      - 'lib/**'
      - 'platformio.ini'
      - 'partitions_16mb_ota.csv'
      - '.github/workflows/build-remote.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Use remote firmware source
        run: |
          cp remote/src/main.cpp src/main.cpp
          cp remote/src/pin_config.h src/pin_config.h

      - name: Build remote firmware
        run: pio run

      - name: Rename remote firmware
        run: |
          mkdir -p output
          cp .pio/build/waterwatch_host_18/firmware.bin output/WaterWatchPro_REMOTE_firmware.bin

      - name: Upload remote firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: WaterWatchPro-Remote-Firmware
          path: output/WaterWatchPro_REMOTE_firmware.bin
